import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { CartContextProvider } from "./context/cart";
import { ThemeContextProvider } from "./context/theme";
import "./globals.css";

export const metadata = {
  title: "Plantif",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="bg-white dark:bg-[#0C0C0C]">
        <ThemeContextProvider>
          <CartContextProvider>
            <main className="max-w-screen-2xl mx-auto">
              <Navbar />
              <div className="font-serif">{children}</div>
              <Footer />
            </main>
          </CartContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
